# Generated by Django 5.2.7 on 2025-10-17 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="shmavito.customerstatus",
                verbose_name="Статус пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tg_id",
            field=models.IntegerField(null=True, verbose_name="ID в Telegram"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="tg_name",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Имя пользователя Telegram"
            ),
        ),
    ]
