# Generated by Django 5.2.7 on 2025-10-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0002_alter_customer_status_alter_customer_tg_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Одежда", max_length=25, verbose_name="Категория товара"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="good",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="good",
                to="shmavito.goodcategory",
                verbose_name="Категория товара",
            ),
            preserve_default=False,
        ),
    ]
