# Generated by Django 5.2.7 on 2025-10-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0003_goodcategory_good_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodimage",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="images",
                to="shmavito.imagestatus",
                verbose_name="Статус фотографии",
            ),
        ),
    ]
