# Generated by Django 5.2.7 on 2025-10-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0004_alter_goodimage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="customer",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="good",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
    ]
