# Generated by Django 5.2.7 on 2025-10-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0005_good_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата создания товара"),
        ),
    ]
