# Generated by Django 5.2.7 on 2025-10-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0007_goodstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="good",
                to="shmavito.goodstatus",
                verbose_name="Статус товара",
            ),
        ),
    ]
