# Generated by Django 5.2.7 on 2025-11-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0008_good_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="moderate",
            field=models.BooleanField(default=False, verbose_name="Прошел модерацию"),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Стоимость одного дня предложения",
            ),
        ),
    ]
