# Generated by Django 5.2.7 on 2025-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0009_good_moderate_alter_advertisement_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="moderate",
            field=models.IntegerField(default=0, verbose_name="Ожидает модерацию"),
        ),
    ]
