# Generated by Django 5.2.7 on 2025-11-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0010_alter_good_moderate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="moderate",
            field=models.IntegerField(default=0, verbose_name="Ожидает модерацию"),
        ),
    ]
