# Generated by Django 5.2.7 on 2025-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0011_alter_advertisement_moderate"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="isModerator",
            field=models.BooleanField(
                default=False, verbose_name="Пользователь является модератором"
            ),
        ),
    ]
