# Generated by Django 5.2.7 on 2025-11-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0012_customer_ismoderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="buyer",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buyer_comment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Покупатель",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=3,
                max_digits=3,
                verbose_name="Рейтинг пользователя",
            ),
        ),
        migrations.CreateModel(
            name="CustomerScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="Оценка")),
                (
                    "date",
                    models.DateField(
                        auto_now=True, verbose_name="Дата простановки оценки"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_rating",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_rating",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="shmavito.customerscore",
                verbose_name="Оценка пользователя",
            ),
            preserve_default=False,
        ),
    ]
