# Generated by Django 5.2.7 on 2025-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0013_comment_buyer_customer_rating_customerscore_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="moderate",
            field=models.IntegerField(default=0, verbose_name="Модерация комментария"),
        ),
    ]
