# Generated by Django 5.2.7 on 2025-11-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0015_advertisementstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advs",
                to="shmavito.advertisementstatus",
                verbose_name="Статус предложения",
            ),
        ),
        migrations.AlterField(
            model_name="advertisementstatus",
            name="name",
            field=models.CharField(max_length=25, verbose_name="Статус предложения"),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Статус заказа"),
        ),
    ]
