# Generated by Django 5.2.7 on 2025-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shmavito",
            "0016_advertisement_status_alter_advertisementstatus_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Стоимость заказа",
            ),
        ),
    ]
