# Generated by Django 5.2.7 on 2025-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0017_order_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="moderate",
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата комментария"),
        ),
    ]
