# Generated by Django 5.2.7 on 2025-11-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shmavito", "0018_remove_comment_moderate_comment_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="ad",
        ),
        migrations.AddField(
            model_name="comment",
            name="good",
            field=models.ForeignKey(
                default=13,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="shmavito.good",
                verbose_name="Товар",
            ),
            preserve_default=False,
        ),
    ]
